services:
  - type: web
    name: boss-machine
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
